#!/usr/bin/env bash
#
# Copyright © 2023 Aspen James <hello@aspenjames.dev>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# HELPERS
#########

function _confirm() {
  read -p "$1" -n 1 -r reply
  case "$reply" in
    y|Y ) echo && return 0 ;;
    * )   echo && return 1 ;;
  esac
}

# _copyFile source destination [sudo]
# Copies source file to destination, offering to backup if contents differ.
function _copyFile() {
  local src="$1"
  local dest="$2"
  local sudo="$3"
  if [ -f "$dest" ]; then
    if ! cmp -s "$src" "$dest"; then
      if _confirm "Would you like to backup $dest before updating?"; then
        mv "$dest" "${dest}.bak"
      fi
    else
      return 0
    fi
  fi

  if [ "$sudo" ]; then
    _sudo cp "$src" "$dest"
  else
    cp "$src" "$dest"
  fi
}

function _sudo() {
  echo "Executing '$*' as sudo"
  sudo "$@"
}

# Package Manager
#################

function _updatePkgRepos() {
  _sudo apt update
}

function _install() {
  OLDIFS="$IFS"
  IFS=":" read -r -a progs <<< "$1"
  local prog=${progs[0]}
  local exe=${progs[1]:-$prog}

  if [ ! -x "$(command -v "$exe")" ]; then
    echo "Installing $prog..."
    _sudo apt install -y "$prog"
  fi
  IFS="$OLDIFS"
}

# INSTALL
#########

_updatePkgRepos

for prog in \
  build-essential:NULL \
  curl \
  exa \
  git \
  golang:go \
  python3 \
  python3-distutils:NULL \
  ripgrep:rg \
  shellcheck \
  vim \
; do
  _install "$prog"
done

if [ ! -x "$(command -v python)" ]; then
  # Symlink python to python3
  _sudo update-alternatives --install /usr/bin/python python "$(which python3)" 100
fi

if [ ! -x "$(command -v apt-vim)" ]; then
  echo "Installing apt-vim..."
  curl -sL https://raw.githubusercontent.com/egalpin/apt-vim/master/install.sh | sh
  sed -i '/\.vimpkg\/bin/d' "$HOME/.bashrc"
fi

# CONFIGURE
###########

# Profile
#########
for file in files/profile.d/*.sh; do
  _copyFile "$file" "/etc/profile.d/$(basename "$file")" sudo
done

# Git
#####
_copyFile files/gitconfig "$HOME/.gitconfig"

# Vim
#####
_copyFile files/vimrc "$HOME/.vimrc"
